# Sign Up
POST http://ey-chat.dev/api/users/signup
content-type: application/json

{ 
  "username": "test",
  "password": "test"
}

###
# Sign in
POST https://ey-chat.dev/api/users/signin
content-type: application/json

{
  "username": "test",
  "password": "test"
}

###
# Current User
GET https://ey-chat.dev/api/users/currentuser

###
#New Message
POST https://ey-chat.dev/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOWMwNTJhMzQ1NjhiMDAxYThlOTYzMCIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTYyMDgzNzY3NX0.yOxzdypj1p-5CC6iR8zpT25CAakburZnUfgMaIgt7F0

{
  "groupId": "609c056b009bb600199f6a57",
  "sender": "test",
  "payload": "How are you?"
}

###
#Create Group
POST https://ey-chat.dev/api/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOWMwNTJhMzQ1NjhiMDAxYThlOTYzMCIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTYyMDgzNzY3NX0.yOxzdypj1p-5CC6iR8zpT25CAakburZnUfgMaIgt7F0

{
  "name": "group 1",
  "users": ["hi","test"]
}

###
#Index Participant
GET http://localhost/api/participants/groups

###
#Get messages
GET http://localhost/api/messages/60995174aadec7001a4ea497?lastCreatedAt=undefined