# Sign Up
POST http://ey-chat.dev/api/users/signup
content-type: application/json

{ 
  "username": "test",
  "password": "test"
}

###
# Sign in
POST https://ey-chat.dev/api/users/signin
content-type: application/json

{
  "username": "test",
  "password": "test"
}

###
# Current User
GET https://ey-chat.dev/api/users/currentuser

###
#New Message
POST https://ey-chat.dev/api/messages
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOWU5NGJiMjUwYjkyMDAxYjZkODM4NiIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTYyMTAwNTQ5OX0.7laonxuyob4WjnaWiGaLDTPe8Yjc1Gn4RxhuSmNJPcc

{
  "groupId": "609e95034bfa52001a5fd3e4",
  "sender": "test",
  "payload": "Hello"
}

###
#Create Group
POST https://ey-chat.dev/api/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwOWU5NGJiMjUwYjkyMDAxYjZkODM4NiIsInVzZXJuYW1lIjoidGVzdCIsImlhdCI6MTYyMTAwNTQ5OX0.7laonxuyob4WjnaWiGaLDTPe8Yjc1Gn4RxhuSmNJPcc

{
  "name": "group 2",
  "users": ["hi","test"]
}

###
#Index Participant
GET http://localhost/api/participants/groups

###
#Get messages
GET http://localhost/api/messages/60995174aadec7001a4ea497?lastCreatedAt=undefined