apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/proxy-read-timeout: '3600'
    nginx.ingress.kubernetes.io/proxy-send-timeout: '3600'
spec:
  rules:
    - http:
        paths:
          - path: /api/messages/?(.*)
            pathType: Prefix
            backend:
              service:
                name: messages-svc
                port:
                  number: 3000
          - path: /api/?(participants|groups)/?(.*)
            pathType: Prefix
            backend:
              service:
                name: groups-svc
                port:
                  number: 3000
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: auth-svc
                port:
                  number: 3000
          - path: /sockets/?(.*)
            pathType: Prefix
            backend:
              service:
                name: sockets-svc
                port:
                  number: 3000
          - path: /socket.io/?(.*)
            pathType: Prefix
            backend:
              service:
                name: sockets-svc
                port:
                  number: 3000
