apiVersion: apps/v1
kind: Deployment
metadata:
  name: messages-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messages
  template:
    metadata:
      labels:
        app: messages
    spec:
      containers:
        - name: messages
          image: youngethan4/messages
          env:
            - name: KAFKA_HOST
              value: kafka-svc:9092
            - name: MONGO_URI
              value: mongodb://messages-mongo-svc:27017/messages
            - name: JWT_KEY
              value: jwt-test-key
---
apiVersion: v1
kind: Service
metadata:
  name: messages-svc
spec:
  selector:
    app: messages
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000
